### ISSUE TITLE
How to select the pop up buffer and set it to special mode according to a regexp?

### ISSUE THREAD

**Issue by QiangF** [m2ym/popwin-el#125]
Hello everyone,
I tried to set \:noselect to nil, but it doesn't work.
Here is my setting:
(push '(special-buffer-regexp :regexp t :noselect nil)
	  popwin:special-display-config)
(defvar special-buffer-regexp
  '("[*].*result.*[*]\\|[*].*out.*[*]")
  "Regexp of special mode buffer names")
Thank you for your help.

**Comment by m2ym** [comment]
You should unquote the variable like this:

```
(push `(,special-buffer-regexp :regexp t :noselect nil)
	  popwin:special-display-config)
```
