### ISSUE TITLE
Helm integration broken

### ISSUE THREAD

**Issue by Pitometsu** [m2ym/popwin-el#129]
![screenshot](http://i.imgur.com/tsWk9rX.png)
On pop-up `helm` buffer it erase all other windows and split current window by two.
[Issue](https://github.com/emacs-helm/helm/issues/1239) for *Helm*.

**Comment by Pitometsu** [comment]
Fixed by *helm* configuration.

**Comment by m2ym** [comment]
I have the configuration:

    (setq helm-display-function 'popwin:pop-to-buffer)
